<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>ImportHost</AssemblyName>
    <RootNamespace>ImportHost</RootNamespace>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <OutputPath>bin\ImportHost\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <DebugType>portable</DebugType>
    <Deterministic>false</Deterministic>
  </PropertyGroup>

</Project>
